import Core
import GRDBQuery
import SwiftUI

/// Region wrapping the stateless `AnnotationSheet` with the live GRDB
/// query that feeds it and the per-card mutation seams the sheet's
/// callbacks need.
///
/// The container owns no `@Observable` view model. Per Bible AGENTS
/// "reactive vs imperative reads" the projection of DB rows into UI is a
/// `@Query` binding at the view layer — the LLM tool, the in-chat
/// orchestrator, the bulk runner, and the sheet's own regenerate path
/// can all write rows that this query picks up automatically. Transient
/// state (`isGenerating`) is owned by the parent `BibleScreen` so the
/// disclaimer gate and the toast queue can sequence with it; the
/// container is otherwise stateless.
///
/// The container projects each `BibleAnnotationRecord` into one
/// `AnnotationSheet.Card`:
///
/// - `.prose`-rendering categories render the body as inline markdown
///   (`AnnotationBlock` handles the conversion).
/// - `.citation`-rendering rows (`category == .reference`) pass the body
///   through `BibleCitationParser` so a parsed `ParsedCitation` reaches
///   the sheet's reference card; an unresolvable body lands as a
///   plain-text fallback inside the card.
///
/// The provenance footer is composed here from `modelId` + `createdAt`.
/// Empty `modelId` (the seed default before PR 4 wires the active LLM
/// session) renders as `"Generated by AI · <date>"`.
struct AnnotationSheetContainer: View {
    /// Identifies which target's rows this sheet renders.
    let spec: BibleAnnotationTargetSpec
    /// Human-readable header citation, e.g. `"Romans 8:28-30"`. Built by
    /// the parent because the citation formatter needs the book's display
    /// name (which the parent already has from the view model).
    let citation: String
    /// Catalog used to resolve reference-card citations to
    /// `BiblePosition`s. Same catalog the view model uses so book-id
    /// matching stays consistent.
    let catalog: BibleBookCatalog
    /// Write seam for per-card deletion. `nil` disables the per-card
    /// delete action — used only in previews / tests with no database.
    let repository: (any BibleAnnotationRepository)?
    /// Per-target dispatch status from `BibleScreenViewModel`. `nil`
    /// means no headless dispatch is running or failed for this
    /// target — the sheet renders the regular empty / populated
    /// layouts. `.running` shows the generating state, taking
    /// precedence over populated cards so a regenerate hides the stale
    /// cards behind the spinner. `.failed` flips the *empty* layout to
    /// the error + retry button, but stays suppressed while `records`
    /// is non-empty (populated wins) — that regenerate-failure case
    /// routes `onRegenerateFailed` instead, so the previous cards
    /// reappear alongside a toast.
    let dispatchStatus: BibleAnnotationDispatchStatus?
    let bottomInset: CGFloat
    let onRegenerate: () -> Void
    let onAddAllToChat: ([BibleAnnotationRecord]) -> Void
    let onCardAddToChat: (BibleAnnotationRecord) -> Void
    let onOpenReference: (BibleCitationParser.ParsedCitation) -> Void
    /// Tap on the empty-state retry button. Fired only when
    /// `dispatchStatus == .failed(...)`. Routed to the view model's
    /// `retryAnnotationGeneration(for:)`.
    let onRetry: () -> Void
    /// Fired when a per-card delete write fails. The parent surfaces this
    /// as a toast so the user gets feedback instead of the silent "tap
    /// did nothing" the @Query would otherwise produce (the row would
    /// still be there, so the card wouldn't disappear). `nil` swallows
    /// the error — used only by previews / driver views.
    let onCardDeleteFailed: ((any Error) -> Void)?
    /// Fired when a dispatch fails *while existing cards are on screen*
    /// (a regenerate, not a first generation). The sheet keeps showing
    /// the still-present previous cards — they were never deleted — so
    /// this routes a toast + status-clear to the parent for feedback.
    /// First-generation failures (no existing rows) skip this and render
    /// the inline error + retry state instead. Production must always
    /// supply it (`BibleScreen` does) — a `nil` here would leave a
    /// regenerate failure on stale cards with a lingering `.failed`
    /// status and no feedback. `nil` is for previews / driver views only.
    let onRegenerateFailed: (() -> Void)?

    @Query<BibleAnnotationsByTargetRequest> private var records: [BibleAnnotationRecord]

    init(
        spec: BibleAnnotationTargetSpec,
        citation: String,
        catalog: BibleBookCatalog,
        repository: (any BibleAnnotationRepository)?,
        onRegenerate: @escaping () -> Void,
        onAddAllToChat: @escaping ([BibleAnnotationRecord]) -> Void,
        onCardAddToChat: @escaping (BibleAnnotationRecord) -> Void,
        onOpenReference: @escaping (BibleCitationParser.ParsedCitation) -> Void,
        onRetry: @escaping () -> Void = {},
        onCardDeleteFailed: ((any Error) -> Void)? = nil,
        onRegenerateFailed: (() -> Void)? = nil,
        dispatchStatus: BibleAnnotationDispatchStatus? = nil,
        bottomInset: CGFloat = 0
    ) {
        self.spec = spec
        self.citation = citation
        self.catalog = catalog
        self.repository = repository
        self.onRegenerate = onRegenerate
        self.onAddAllToChat = onAddAllToChat
        self.onCardAddToChat = onCardAddToChat
        self.onOpenReference = onOpenReference
        self.onRetry = onRetry
        self.onCardDeleteFailed = onCardDeleteFailed
        self.onRegenerateFailed = onRegenerateFailed
        self.dispatchStatus = dispatchStatus
        self.bottomInset = bottomInset
        self._records = Query(constant: BibleAnnotationsByTargetRequest(spec: spec))
    }

    var body: some View {
        AnnotationSheet(
            citation: citation,
            cards: cards,
            onRegenerate: onRegenerate,
            onAddAllToChat: { onAddAllToChat(records) },
            onCardAddToChat: { id in
                guard let record = records.first(where: { $0.id == id }) else { return }
                onCardAddToChat(record)
            },
            onCardDelete: { id in
                guard let repository else { return }
                Task {
                    do {
                        try await repository.deleteOne(id: id)
                    } catch {
                        onCardDeleteFailed?(error)
                    }
                }
            },
            onOpenReference: onOpenReference,
            onRetry: onRetry,
            isGenerating: isGeneratingFromStatus,
            errorMessage: errorMessageFromStatus,
            bottomInset: bottomInset
        )
        // A dispatch failed while cards are still on screen — a
        // regenerate, not a first generation. The sheet keeps rendering
        // the cards (populated wins over the error layout), so route a
        // toast + status-clear to the parent rather than silently
        // leaving the stale `.failed` status. First-generation failures
        // (no cards) render the inline error + retry state instead, so
        // we leave those alone. `initial: true` covers a sheet
        // re-opened onto an already-`.failed` status (dismissed mid
        // regenerate, failed in the background); reacting to the
        // combined `records`/status signal covers the `@Query`
        // delivering `records` after mount.
        .onChange(of: hasRegenerateFailureWithCards, initial: true) { _, failed in
            if failed { onRegenerateFailed?() }
        }
    }

    /// `true` while a dispatch has failed *and* cards are still on
    /// screen — the regenerate-failure case the parent surfaces as a
    /// toast. A first-generation failure (no rows) is `false` here and
    /// renders the inline error + retry layout instead.
    private var hasRegenerateFailureWithCards: Bool {
        errorMessageFromStatus != nil && !records.isEmpty
    }

    /// `.running` → spinner; other states → no spinner.
    private var isGeneratingFromStatus: Bool {
        if case .running = dispatchStatus { return true }
        return false
    }

    /// `.failed(message)` → error variant carrying `message`; other
    /// states → no error variant. The sheet itself suppresses the
    /// error layout when `records` is non-empty so a late-arriving
    /// failure event doesn't hide already-rendered cards.
    private var errorMessageFromStatus: String? {
        if case .failed(let message) = dispatchStatus { return message }
        return nil
    }

    private var cards: [AnnotationSheet.Card] {
        records.map { record in
            AnnotationSheet.Card(
                id: record.id,
                category: record.category,
                title: record.title,
                content: makeContent(for: record),
                provenance: makeProvenance(for: record)
            )
        }
    }

    private func makeContent(for record: BibleAnnotationRecord) -> AnnotationBlock.Content {
        switch record.category.rendering {
        case .prose:
            return .text(record.body)
        case .citation:
            return .reference(
                label: record.body,
                target: BibleCitationParser.parse(record.body, in: catalog)
            )
        }
    }

    /// Pre-formatted provenance line, e.g.
    /// `"Generated by AFM 3.0 · Nov 27, 2026"`. Empty `modelId` (the
    /// pre-PR-4 default before the live LLM session id is wired through)
    /// renders as `"Generated by AI"` so the footer still reads sensibly.
    private func makeProvenance(for record: BibleAnnotationRecord) -> String {
        let model = record.modelId.isEmpty ? "AI" : record.modelId
        let date = Self.provenanceDateFormatter.string(from: record.createdAt)
        return "Generated by \(model) · \(date)"
    }

    /// Shared formatter for provenance dates. Created once because
    /// `DateFormatter` is expensive to allocate and the sheet may render
    /// many cards.
    private static let provenanceDateFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.dateStyle = .medium
        formatter.timeStyle = .none
        return formatter
    }()
}
