import Core
import GRDBQuery
import SwiftUI

/// Region wrapping the stateless `AnnotationSheet` with the live GRDB
/// query that feeds it and the mutation seams the sheet's callbacks need.
///
/// The container owns no `@Observable` view model. Per Bible AGENTS
/// "reactive vs imperative reads" the projection of DB rows into UI is a
/// `@Query` binding at the view layer — the LLM tool, the in-chat
/// orchestrator, the bulk runner, and the sheet's own regenerate path
/// can all write rows that this query picks up automatically. Transient
/// state (`isGenerating`) is owned by the parent `BibleScreen` so the
/// disclaimer gate and the toast queue can sequence with it; the
/// container is otherwise stateless.
///
/// The container projects the target's `BibleAnnotationRecord` into the
/// sheet's single `Card` — the *newest* row defensively, since `replace`
/// semantics make one-row-per-target the steady state (a stray duplicate
/// is harmless and converges on the next regenerate or delete). The verse
/// text is passed in by the parent as a plain `String?` (the screen's view
/// model owns the text loader), keeping the container preview/snapshot-
/// friendly with no loader dependency.
///
/// The provenance footer is composed here from `modelId` + `createdAt`.
/// Empty `modelId` renders as `"Generated by AI · <date>"`.
struct AnnotationSheetContainer: View {
    /// Identifies which target's rows this sheet renders.
    let spec: BibleAnnotationTargetSpec
    /// Human-readable citation, e.g. `"Romans 8:28-30"` — the nav-bar
    /// title and the card's heading. Built by the parent because the
    /// citation formatter needs the book's display name (which the
    /// parent already has from the view model).
    let citation: String
    /// Plain verse text for verse-range targets, `nil` for chapter/book
    /// targets or when the text failed to load. Computed by the parent
    /// at presentation time.
    let verseText: String?
    /// Write seam for deletion. `nil` disables the delete action —
    /// used only in previews / tests with no database.
    let repository: (any BibleAnnotationRepository)?
    /// Per-target dispatch status from `BibleScreenViewModel`. `nil`
    /// means no headless dispatch is running or failed for this
    /// target — the sheet renders the regular empty / populated
    /// layouts. `.running` shows the generating state, taking
    /// precedence over a populated card so a regenerate hides the stale
    /// card behind the spinner. `.failed` flips the *empty* layout to
    /// the error + retry button, but stays suppressed while `records`
    /// is non-empty (populated wins) — that regenerate-failure case
    /// routes `onRegenerateFailed` instead, which clears the stale status
    /// so the previous card stays (no toast — the failure is silent).
    let dispatchStatus: BibleAnnotationDispatchStatus?
    let bottomInset: CGFloat
    /// Dismisses the sheet from the nav bar's leading close button.
    let onClose: () -> Void
    let onRegenerate: () -> Void
    /// "Add to chat" from the sheet kebab, carrying the rendered record.
    let onAddToChat: (BibleAnnotationRecord) -> Void
    /// A `super://bible/...` citation link inside the summary was
    /// tapped. Routed to the view model's reader navigation.
    let onOpenLink: (BibleDeepLink) -> Void
    /// Tap on the empty-state retry button. Fired only when
    /// `dispatchStatus == .failed(...)`. Routed to the view model's
    /// `retryAnnotationGeneration(for:)`.
    let onRetry: () -> Void
    /// Fired when the delete write fails. The parent surfaces this
    /// as a toast so the user gets feedback instead of the silent "tap
    /// did nothing" the @Query would otherwise produce (the row would
    /// still be there, so the card wouldn't disappear). `nil` swallows
    /// the error — used only by previews / driver views.
    let onDeleteFailed: ((any Error) -> Void)?
    /// Fired when a dispatch fails *while an existing card is on screen*
    /// (a regenerate, not a first generation). The sheet keeps showing
    /// the still-present previous card — it was never deleted — so
    /// this routes a status-clear to the parent (no toast: the failure is
    /// silent, the card stays). Clearing the lingering `.failed` status
    /// also stops the sheet flipping to the inline error+retry layout if
    /// the user later deletes the remaining card. First-generation
    /// failures (no existing rows) skip this and render the inline error +
    /// retry state instead. Production must always supply it (`BibleScreen`
    /// does) — a `nil` here would leave a regenerate failure on a stale card
    /// with a lingering `.failed` status. `nil` is for previews / driver
    /// views only.
    let onRegenerateFailed: (() -> Void)?

    @Query<BibleAnnotationsByTargetRequest> private var records: [BibleAnnotationRecord]

    init(
        spec: BibleAnnotationTargetSpec,
        citation: String,
        verseText: String?,
        repository: (any BibleAnnotationRepository)?,
        onClose: @escaping () -> Void,
        onRegenerate: @escaping () -> Void,
        onAddToChat: @escaping (BibleAnnotationRecord) -> Void,
        onOpenLink: @escaping (BibleDeepLink) -> Void,
        onRetry: @escaping () -> Void = {},
        onDeleteFailed: ((any Error) -> Void)? = nil,
        onRegenerateFailed: (() -> Void)? = nil,
        dispatchStatus: BibleAnnotationDispatchStatus? = nil,
        bottomInset: CGFloat = 0
    ) {
        self.spec = spec
        self.citation = citation
        self.verseText = verseText
        self.repository = repository
        self.onClose = onClose
        self.onRegenerate = onRegenerate
        self.onAddToChat = onAddToChat
        self.onOpenLink = onOpenLink
        self.onRetry = onRetry
        self.onDeleteFailed = onDeleteFailed
        self.onRegenerateFailed = onRegenerateFailed
        self.dispatchStatus = dispatchStatus
        self.bottomInset = bottomInset
        self._records = Query(constant: BibleAnnotationsByTargetRequest(spec: spec))
    }

    var body: some View {
        AnnotationSheet(
            citation: citation,
            card: card,
            onClose: onClose,
            onRegenerate: onRegenerate,
            onAddToChat: {
                guard let record = renderedRecord else { return }
                onAddToChat(record)
            },
            onDelete: {
                guard let repository else { return }
                // `replace` with no inserts is the repository's atomic
                // whole-target clear: one transaction deletes every row
                // for the target (converging stray duplicates), so a
                // failure leaves either everything or nothing — never a
                // half-deleted group under a "delete failed" toast.
                let spec = spec
                Task {
                    do {
                        try await repository.replace(
                            target: spec.target,
                            bookId: spec.bookId,
                            chapterNumber: spec.chapterNumber,
                            verseStart: spec.verseStart,
                            verseEnd: spec.verseEnd,
                            inserting: []
                        )
                    } catch {
                        onDeleteFailed?(error)
                    }
                }
            },
            onOpenLink: onOpenLink,
            onRetry: onRetry,
            isGenerating: isGeneratingFromStatus,
            errorMessage: errorMessageFromStatus,
            bottomInset: bottomInset
        )
        // A dispatch failed while a card is still on screen — a
        // regenerate, not a first generation. The sheet keeps rendering
        // the card (populated wins over the error layout), so route a
        // status-clear to the parent rather than leaving the stale
        // `.failed` status (no toast — the failure is silent). First-
        // generation failures (no card) render the inline error + retry
        // state instead, so we leave those alone. `initial: true` covers a sheet
        // re-opened onto an already-`.failed` status (dismissed mid
        // regenerate, failed in the background); reacting to the
        // combined `records`/status signal covers the `@Query`
        // delivering `records` after mount.
        .onChange(of: hasRegenerateFailureWithCard, initial: true) { _, failed in
            if failed { onRegenerateFailed?() }
        }
    }

    /// `true` while a dispatch has failed *and* a card is still on
    /// screen — the regenerate-failure case the parent clears the stale
    /// status for (silently, no toast). A first-generation failure (no
    /// rows) is `false` here and renders the inline error + retry layout
    /// instead.
    private var hasRegenerateFailureWithCard: Bool {
        errorMessageFromStatus != nil && !records.isEmpty
    }

    /// `.running` → spinner; other states → no spinner.
    private var isGeneratingFromStatus: Bool {
        if case .running = dispatchStatus { return true }
        return false
    }

    /// `.failed(message)` → error variant carrying `message`; other
    /// states → no error variant. The sheet itself suppresses the
    /// error layout when `records` is non-empty so a late-arriving
    /// failure event doesn't hide an already-rendered card.
    private var errorMessageFromStatus: String? {
        if case .failed(let message) = dispatchStatus { return message }
        return nil
    }

    /// The row the sheet renders. Ordering is `(createdAt ASC, id ASC)`,
    /// so `.last` is the *newest* row — if a stray duplicate ever
    /// appears (a non-replace writer, a future sync merge), the user
    /// sees the latest generation rather than a stale one that makes
    /// every regenerate look like it "didn't take".
    private var renderedRecord: BibleAnnotationRecord? { records.last }

    /// The single card projection (see the type doc).
    private var card: AnnotationSheet.Card? {
        guard let record = renderedRecord else { return nil }
        return AnnotationSheet.Card(
            title: citation,
            verseText: verseText,
            summary: record.summary,
            provenance: makeProvenance(for: record)
        )
    }

    /// Pre-formatted provenance line, e.g.
    /// `"Generated by AFM 3.0 · Nov 27, 2026"`. Empty `modelId`
    /// renders as `"Generated by AI"` so the footer still reads sensibly.
    private func makeProvenance(for record: BibleAnnotationRecord) -> String {
        let model = record.modelId.isEmpty ? "AI" : record.modelId
        let date = Self.provenanceDateFormatter.string(from: record.createdAt)
        return "Generated by \(model) · \(date)"
    }

    /// Shared formatter for provenance dates. Created once because
    /// `DateFormatter` is expensive to allocate.
    private static let provenanceDateFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.dateStyle = .medium
        formatter.timeStyle = .none
        // Track the user's live locale rather than freezing at whichever
        // locale first touched this static (same fix as the Notes list's
        // formatter).
        formatter.locale = Locale.autoupdatingCurrent
        return formatter
    }()
}
