import Core
import SwiftUI

/// The single annotation card rendered inside `AnnotationSheet`.
///
/// Anatomy (top to bottom):
///
/// - **Title**: the scripture citation (`"Romans 8:28–30"`, `"Romans 8"`,
///   `"Romans"`) in the EB Garamond reading face's SemiBold member.
/// - **Verse text** (verse-range targets only): the passage itself,
///   rendered with the exact reader recipe — `@ScaledMetric` body over
///   `typography.reading` plus `BibleReadingMetrics.lineSpacing` — behind
///   a thin leading rule (a blockquote affordance separating scripture
///   from commentary). Chapter/book cards omit this region.
/// - **Summary**: the record's long-form markdown through the shared
///   `Core.MarkdownText` renderer, so annotation prose paints with the
///   same faces, palette, and block chrome as Chat's assistant messages.
///   Scripture citations inside the summary are auto-linkified; the
///   sheet intercepts the resulting `super://bible/...` taps.
/// - **Footer**: a small mute-ink provenance line, pre-formatted by the
///   caller (e.g. `"Generated by AFM 3.0 · Nov 27, 2026"`).
///
/// The block is stateless and carries no actions — Regenerate / Add to
/// chat / Delete live in the sheet's nav-bar kebab, since the sheet hosts
/// exactly one card.
struct AnnotationBlock: View {
    @Environment(\.superTheme) private var theme
    @Environment(\.superTypography) private var typography

    /// Reader-matched verse body size: OS Dynamic Type folds in via
    /// `@ScaledMetric`, the app font-scale slider via
    /// `typography.reading`'s own scaling — the same dual-axis recipe as
    /// `BibleParagraphBlock`, so the quoted text is pixel-consistent
    /// with the chapter the user just left.
    @ScaledMetric(relativeTo: .body) private var verseBodySize: CGFloat = SuperTypography.readingBodySize

    /// The citation title, e.g. `"Romans 8:28-30"`.
    let title: String
    /// The target's verse text, plain-joined without verse numbers.
    /// `nil` for chapter/book targets (and when the text failed to
    /// load) — the card degrades to title + summary.
    let verseText: String?
    /// Long-form markdown study summary.
    let summary: String
    let provenance: String

    var body: some View {
        VStack(alignment: .leading, spacing: 14) {
            Text(title)
                .font(typography.reading(22, relativeTo: .title2, weight: .semibold))
                .foregroundStyle(theme.ink)
                .fixedSize(horizontal: false, vertical: true)
            if let verseText {
                verseTextBlock(verseText)
            }
            // The shared renderer scales off `\.markdownBodyMetrics` and
            // emits `super://bible/...` citation links — both supplied by
            // the host's `bibleMarkdownRendering(openLink:)` modifier
            // (the sheet applies it), not by this leaf view.
            MarkdownText(summary)
                .frame(maxWidth: .infinity, alignment: .leading)
            footer
        }
        .padding(.horizontal, 16)
        .padding(.vertical, 16)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(
            RoundedRectangle(cornerRadius: 16)
                .fill(theme.backgroundRaised)
        )
        .overlay(
            RoundedRectangle(cornerRadius: 16)
                .strokeBorder(theme.borderFaint, lineWidth: 0.5)
        )
    }

    /// The quoted passage behind a thin leading rule. Rendered exactly
    /// like reader prose (face, size, leading) so the quote reads as
    /// scripture, not commentary.
    private func verseTextBlock(_ text: String) -> some View {
        Text(text)
            .font(typography.reading(verseBodySize, relativeTo: nil))
            .lineSpacing(BibleReadingMetrics.lineSpacing(bodySize: verseBodySize, fontScale: typography.fontScale))
            .foregroundStyle(theme.ink)
            .fixedSize(horizontal: false, vertical: true)
            .frame(maxWidth: .infinity, alignment: .leading)
            .padding(.leading, 12)
            .overlay(alignment: .leading) {
                Rectangle()
                    .fill(theme.borderFaint)
                    .frame(width: 3)
            }
    }

    private var footer: some View {
        Text(provenance)
            .font(typography.font(size: 10, weight: .regular, design: .monospaced))
            .tracking(0.3)
            .foregroundStyle(theme.inkMute)
            .lineLimit(1)
            .padding(.top, 2)
    }
}
