import Core
import SwiftUI

/// One annotation card rendered inside `AnnotationSheet`.
///
/// Anatomy mirrors the Claude Design canvas (`sheet.jsx`):
///
/// - **Header**: a small uppercase monospaced title (left) and a kebab
///   menu button (right). The menu carries "Add to chat" + the
///   destructive "Delete this card".
/// - **Body**: one of three shapes per `body`:
///     - `.text` — inline-markdown prose (`AttributedString(markdown:)`).
///     - `.reference(label:, target: .some)` — a tinted pill button with
///       the citation label + an `arrow.up.forward` glyph. Tap fires
///       `onOpenReference(...)`.
///     - `.reference(label:, target: nil)` — the parser couldn't resolve
///       the citation; render `label` as plain inline text so the body
///       still surfaces, just without the deep-link affordance.
/// - **Footer**: a small mute-ink provenance line, pre-formatted by the
///   caller (e.g. `"Generated by AFM 3.0 · Nov 27, 2026"`).
///
/// The block is stateless: menu open/closed is local `@State` and all
/// side effects go through the three injected callbacks.
struct AnnotationBlock: View {
    @Environment(\.superTheme) private var theme

    /// Card body content. The reference case carries both the display
    /// label (what to show) and the parsed citation target (where to
    /// navigate when tapped). `nil` target means the parser failed.
    ///
    /// The enum is named `Content` rather than `Body` to avoid shadowing
    /// SwiftUI's `View.body` requirement on this same type.
    enum Content: Sendable, Equatable {
        case text(String)
        case reference(label: String, target: BibleCitationParser.ParsedCitation?)
    }

    let title: String
    let content: Content
    let provenance: String
    let onAddToChat: () -> Void
    let onDelete: () -> Void
    let onOpenReference: (BibleCitationParser.ParsedCitation) -> Void

    /// Local gate for the destructive-delete confirmation dialog. The
    /// kebab's "Delete this card" sets it true; the dialog's "Delete"
    /// then fires `onDelete`. Per iOS HIG, non-reversible destructive
    /// actions in menus get a confirmation step.
    @State private var showDeleteConfirmation: Bool = false

    init(
        title: String,
        content: Content,
        provenance: String,
        onAddToChat: @escaping () -> Void,
        onDelete: @escaping () -> Void,
        onOpenReference: @escaping (BibleCitationParser.ParsedCitation) -> Void
    ) {
        self.title = title
        self.content = content
        self.provenance = provenance
        self.onAddToChat = onAddToChat
        self.onDelete = onDelete
        self.onOpenReference = onOpenReference
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 6) {
            header
            contentView
            footer
        }
        .padding(.horizontal, 16)
        .padding(.vertical, 14)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(
            RoundedRectangle(cornerRadius: 16)
                .fill(theme.backgroundRaised)
        )
        .overlay(
            RoundedRectangle(cornerRadius: 16)
                .strokeBorder(theme.borderFaint, lineWidth: 0.5)
        )
        .confirmationDialog(
            "Delete this annotation card?",
            isPresented: $showDeleteConfirmation,
            titleVisibility: .visible
        ) {
            Button("Delete card", role: .destructive, action: onDelete)
            Button("Cancel", role: .cancel) { }
        } message: {
            Text("This card will be permanently removed.")
        }
    }

    private var header: some View {
        HStack(alignment: .center, spacing: 8) {
            Text(title.uppercased())
                .font(.system(size: 10, weight: .medium, design: .monospaced))
                .tracking(0.7)
                .foregroundStyle(theme.inkFaint)
                .lineLimit(1)
            Spacer()
            Menu {
                Button(action: onAddToChat) {
                    Label("Add to chat", systemImage: "paperplane")
                }
                Button(role: .destructive, action: { showDeleteConfirmation = true }) {
                    Label("Delete this card", systemImage: "trash")
                }
            } label: {
                Image(systemName: "ellipsis")
                    .font(.system(size: 14, weight: .medium))
                    .foregroundStyle(theme.inkFaint)
                    .frame(width: 22, height: 22)
                    .contentShape(Rectangle())
            }
            .menuStyle(.borderlessButton)
            .accessibilityLabel("Card actions")
        }
    }

    @ViewBuilder
    private var contentView: some View {
        switch content {
        case .text(let markdown):
            Text(attributed(from: markdown))
                .font(.system(size: 14))
                .lineSpacing(2)
                .foregroundStyle(theme.ink)
                .fixedSize(horizontal: false, vertical: true)
                .frame(maxWidth: .infinity, alignment: .leading)
        case .reference(let label, .some(let target)):
            Button {
                onOpenReference(target)
            } label: {
                HStack(spacing: 6) {
                    Text(label)
                        .font(.system(size: 13.5, weight: .medium))
                    Image(systemName: "arrow.up.forward")
                        .font(.system(size: 11, weight: .semibold))
                }
                .foregroundStyle(theme.accent)
                .padding(.horizontal, 12)
                .padding(.vertical, 6)
                .background(Capsule().fill(theme.accentSoft))
                .contentShape(Capsule())
            }
            .buttonStyle(.plain)
            .accessibilityLabel("Open \(label)")
        case .reference(let label, .none):
            Text(label)
                .font(.system(size: 14))
                .foregroundStyle(theme.ink)
                .frame(maxWidth: .infinity, alignment: .leading)
        }
    }

    private var footer: some View {
        Text(provenance)
            .font(.system(size: 10, weight: .regular, design: .monospaced))
            .tracking(0.3)
            .foregroundStyle(theme.inkMute)
            .lineLimit(1)
            .padding(.top, 4)
    }

    /// Parse inline markdown; fall back to the raw string when the
    /// payload isn't well-formed. The card body is expected to be ≤2
    /// sentences so inline-only (bold/italic/link) markdown is enough —
    /// no block-level rendering needed.
    private func attributed(from markdown: String) -> AttributedString {
        if let attributed = try? AttributedString(markdown: markdown) {
            return attributed
        }
        return AttributedString(markdown)
    }
}
