import Core
import Foundation

/// Resolves the `source` and `modelId` an annotation tool call should
/// stamp on the rows it writes.
///
/// Two reasons this is injected rather than computed inside the tool:
///
/// 1. The bulk runner (M-B / M-C) needs to stamp `.userBulk`, the
///    single-target tap path needs to stamp `.user`. The active session
///    knows which it is; the tool doesn't.
/// 2. `modelId` is whichever LLM (Large Language Model) made the call —
///    information that lives in the active provider registry, not in the
///    tool's input. `ActiveModelBibleAnnotationStampProvider` resolves it
///    from the active provider at execution time; the default returns an
///    empty string for paths with no LLM context (tests, DB-less init).
///
/// `stamp()` is `async` because the production provider reads the active
/// model off the actor-isolated `LLMProviderRegistry`.
///
/// Tests substitute fakes through this seam to assert source-derivation
/// and model-id stamping without spinning up a real LLM session.
public protocol BibleAnnotationStampProvider: Sendable {
    func stamp() async -> BibleAnnotationStamp
}

/// Provenance stamp applied to every row a single tool call writes.
public struct BibleAnnotationStamp: Sendable, Equatable {
    public let source: BibleAnnotationSource
    public let modelId: String

    public init(source: BibleAnnotationSource, modelId: String) {
        self.source = source
        self.modelId = modelId
    }
}

/// Fallback provider for paths with no live LLM context — tests and the
/// DB-less applet init where the annotate tool can't actually run. Stamps
/// `.user` with an empty `modelId`, which the provenance footer renders as
/// "Generated by AI · {date}". Production annotation paths use
/// `ActiveModelBibleAnnotationStampProvider` instead.
public struct DefaultBibleAnnotationStampProvider: BibleAnnotationStampProvider {
    public init() {}
    public func stamp() async -> BibleAnnotationStamp {
        BibleAnnotationStamp(source: .user, modelId: "")
    }
}

/// Stamps annotation rows with the active provider's model id, resolved at
/// tool-execution time off the `LLMProviderRegistry`.
///
/// Every provider maps 1:1 to one model, so the active provider's sole
/// model is the model that generated the card — the same resolution
/// `BibleAnnotateDispatcher` uses to pick the model for the turn. Resolving
/// lazily inside `stamp()` (rather than capturing at registration time)
/// means the id reflects whatever model is active when the annotation is
/// actually written. Falls back to an empty `modelId` (footer: "Generated
/// by AI") when no provider is active.
public struct ActiveModelBibleAnnotationStampProvider: BibleAnnotationStampProvider {
    private let registry: LLMProviderRegistry
    private let source: BibleAnnotationSource

    public init(registry: LLMProviderRegistry, source: BibleAnnotationSource = .user) {
        self.registry = registry
        self.source = source
    }

    public func stamp() async -> BibleAnnotationStamp {
        // Deliberately yoked to `BibleAnnotateDispatcher.resolveActiveModel`'s
        // `supportedModels.first` so the stamped id always matches the model
        // the turn actually ran against. If one side ever stops using `.first`
        // (e.g. real multi-model providers), update both together or they drift.
        let modelId = await registry.active()?.supportedModels.first?.id ?? ""
        return BibleAnnotationStamp(source: source, modelId: modelId)
    }
}
