import Foundation

/// Resolves the `source` and `modelId` an annotation tool call should
/// stamp on the rows it writes.
///
/// Two reasons this is injected rather than computed inside the tool:
///
/// 1. The bulk runner (M-B / M-C) needs to stamp `.userBulk`, the
///    single-target tap path needs to stamp `.user`. The active session
///    knows which it is; the tool doesn't.
/// 2. `modelId` is whichever LLM (Large Language Model) made the call —
///    information that lives in the active Chat session, not in the
///    tool's input. The integration milestone (PR 3) wires a real
///    provider; until then the default returns an empty string so the
///    schema stays satisfied without leaking a placeholder model name.
///
/// Tests substitute fakes through this seam to assert source-derivation
/// and model-id stamping without spinning up a real LLM session.
public protocol BibleAnnotationStampProvider: Sendable {
    func stamp() -> BibleAnnotationStamp
}

/// Provenance stamp applied to every row a single tool call writes.
public struct BibleAnnotationStamp: Sendable, Equatable {
    public let source: BibleAnnotationSource
    public let modelId: String

    public init(source: BibleAnnotationSource, modelId: String) {
        self.source = source
        self.modelId = modelId
    }
}

/// Default provider used in production until the integration milestone
/// (PR 3) wires the active session. Stamps every call as `.user` with an
/// empty `modelId` — the per-card provenance footer reads "Generated by
/// — · {date}" until the real provider lands; functionally correct
/// because the schema permits empty modelId.
public struct DefaultBibleAnnotationStampProvider: BibleAnnotationStampProvider {
    public init() {}
    public func stamp() -> BibleAnnotationStamp {
        BibleAnnotationStamp(source: .user, modelId: "")
    }
}
