#if canImport(UIKit)
import Core
import SnapshotTesting
import SwiftUI
import Testing
@testable import Bible

/// Snapshots of `AnnotationSheet` — the bottom sheet that wraps the
/// annotation cards. Variants cover the empty/generating states across
/// all themes, the loaded 3-card state across all themes, an 8-card
/// state to exercise the scroll overflow, and a Dynamic Type XXL pass.
@Suite("AnnotationSheet snapshots")
@MainActor
struct AnnotationSheetSnapshotTests {
    /// Register Core's bundled brand fonts so the migrated JetBrains Mono /
    /// Instrument Serif chrome faces resolve instead of baking the system
    /// fallback, and so this suite stays order-independent (registration is
    /// process-global; see `SnapshotFontRegistration`).
    init() { SnapshotFontRegistration.ensureRegistered() }

    private static let citation = "Romans 8:28-30"

    // In canonical category order (author → summary → historical), matching
    // what the sheet's query feeds in production.
    private static let threeCards: [AnnotationSheet.Card] = [
        AnnotationSheet.Card(
            id: "a",
            category: .author,
            title: "Author",
            content: .text("Paul, writing from prison in Rome around 60 AD. Romans is the longest of his letters and the most systematic."),
            provenance: "Generated by AFM 3.0 · Nov 27, 2026"
        ),
        AnnotationSheet.Card(
            id: "c",
            category: .summary,
            title: "Summary",
            content: .text("The golden chain of salvation: foreknown, predestined, called, justified, glorified. A pastoral assurance that suffering does not separate believers from God."),
            provenance: "Generated by AFM 3.0 · Nov 27, 2026"
        ),
        AnnotationSheet.Card(
            id: "b",
            category: .historical,
            title: "Historical context",
            content: .text("Written to a church Paul had not yet visited, made up of both Jewish and Gentile believers. Tensions between the two groups frame much of the letter."),
            provenance: "Generated by AFM 3.0 · Nov 27, 2026"
        ),
    ]

    // One card per category in canonical order — exercises every badge glyph
    // (mirrors `annotations/sheet.jsx` `CARDS_CATEGORIES`).
    private static let categoryCards: [AnnotationSheet.Card] = [
        text(id: "auth", category: .author, title: "Author",
             body: "Paul of Tarsus, writing from Corinth around 57 AD — the longest and most systematic of his letters."),
        text(id: "sum", category: .summary, title: "Summary",
             body: "The golden chain of salvation: foreknown, predestined, called, justified, glorified."),
        text(id: "hist", category: .historical, title: "Historical context",
             body: "Addressed to a mixed Jewish-Gentile church in Rome that Paul had not yet visited; their tensions shape the letter."),
        text(id: "clar", category: .clarification, title: "Clarification",
             body: "\"All things work together for good\" is not a promise of pleasant circumstances, but that nothing falls outside God's hand."),
        ref(id: "ref", title: "Cross-reference", label: "Ephesians 1:11",
            target: BibleCitationParser.ParsedCitation(
                position: BiblePosition(bookId: "EPH", chapterNumber: 1),
                verseStart: 11, verseEnd: 11
            )),
    ]

    // In canonical category order (summary → historical → clarification →
    // references), matching what the sheet's query feeds in production; the
    // run of reference cards exercises the scroll overflow.
    private static let eightCards: [AnnotationSheet.Card] = {
        let jhn = BiblePosition(bookId: "JHN", chapterNumber: 1)
        let eph = BiblePosition(bookId: "EPH", chapterNumber: 1)
        return [
            text(id: "7", category: .summary, title: "Parallel",
                 body: "First Peter 1:2 echoes the same chain: chosen, sanctified, sprinkled — the same logic with different verbs."),
            text(id: "3", category: .historical, title: "In context",
                 body: "\"All things\" includes the suffering Paul names in v18–25 — creation's groaning, the believer's weakness in prayer, even persecution."),
            text(id: "4", category: .clarification, title: "Greek note",
                 body: "συνεργεῖ (synergei) — \"works together with.\" The grammar leaves room for God as the actor, or for the things themselves as cooperating under His hand."),
            ref(id: "1", title: "Cross-reference", label: "John 1:14",
                target: BibleCitationParser.ParsedCitation(position: jhn, verseStart: 14, verseEnd: 14)),
            ref(id: "2", title: "Cross-reference", label: "Ephesians 1:11",
                target: BibleCitationParser.ParsedCitation(position: eph, verseStart: 11, verseEnd: 11)),
            ref(id: "5", title: "Parse failed", label: "John 14, verse twelve", target: nil),
            ref(id: "6", title: "See also", label: "Romans 8:39",
                target: BibleCitationParser.ParsedCitation(
                    position: BiblePosition(bookId: "ROM", chapterNumber: 8),
                    verseStart: 39, verseEnd: 39
                )),
            ref(id: "8", title: "Cross-reference", label: "2 Timothy 1:9",
                target: BibleCitationParser.ParsedCitation(
                    position: BiblePosition(bookId: "2TI", chapterNumber: 1),
                    verseStart: 9, verseEnd: 9
                )),
        ]
    }()

    private static func text(
        id: String, category: BibleAnnotationCategory = .clarification,
        title: String, body: String
    ) -> AnnotationSheet.Card {
        AnnotationSheet.Card(
            id: id, category: category, title: title,
            content: .text(body),
            provenance: "Generated by AFM 3.0 · Nov 27, 2026"
        )
    }

    private static func ref(
        id: String, title: String, label: String,
        target: BibleCitationParser.ParsedCitation?
    ) -> AnnotationSheet.Card {
        AnnotationSheet.Card(
            id: id, category: .reference, title: title,
            content: .reference(label: label, target: target),
            provenance: "Generated by AFM 3.0 · Nov 27, 2026"
        )
    }

    // MARK: - Empty states

    @Test("empty sheet renders in the light theme")
    func emptyLight() {
        verify(theme: .light, cards: [], name: "empty_light")
    }

    @Test("empty sheet renders in the dark theme")
    func emptyDark() {
        verify(theme: .dark, cards: [], name: "empty_dark")
    }

    @Test("empty sheet renders in the sepia theme")
    func emptySepia() {
        verify(theme: .sepia, cards: [], name: "empty_sepia")
    }

    @Test("generating empty sheet shows the spinner-state bubble")
    func generatingLight() {
        verify(theme: .light, cards: [], isGenerating: true, name: "generating_light")
    }

    @Test("a regenerate over populated cards hides them behind the generating state in light")
    func generatingOverPopulatedLight() {
        verify(theme: .light, cards: Self.threeCards, isGenerating: true,
               name: "generating_over_populated_light")
    }

    @Test("a regenerate over populated cards hides them behind the generating state in dark")
    func generatingOverPopulatedDark() {
        verify(theme: .dark, cards: Self.threeCards, isGenerating: true,
               name: "generating_over_populated_dark")
    }

    @Test("a regenerate over populated cards hides them behind the generating state in sepia")
    func generatingOverPopulatedSepia() {
        verify(theme: .sepia, cards: Self.threeCards, isGenerating: true,
               name: "generating_over_populated_sepia")
    }

    @Test("the generating-over-populated state reflows its label at Dynamic Type XXL")
    func generatingOverPopulatedLightXXL() {
        verify(theme: .light, cards: Self.threeCards, isGenerating: true,
               dynamicType: .xxLarge, height: 720,
               name: "generating_over_populated_light_xxl")
    }

    // MARK: - Loaded states

    @Test("one card renders without intercard spacing artifacts")
    func oneCardLight() {
        // Per ANNOTATIONS.md §10 the populated-state matrix is 0 / 1 /
        // 3 / 8 cards. The single-card case isolates per-card chrome
        // from the inter-card spacing the multi-card variants exercise.
        verify(theme: .light, cards: [Self.threeCards[0]], name: "one_card_light")
    }

    @Test("one card renders in the dark theme")
    func oneCardDark() {
        verify(theme: .dark, cards: [Self.threeCards[0]], name: "one_card_dark")
    }

    @Test("one card renders in the sepia theme")
    func oneCardSepia() {
        verify(theme: .sepia, cards: [Self.threeCards[0]], name: "one_card_sepia")
    }

    @Test("three cards render in the light theme")
    func threeCardsLight() {
        verify(theme: .light, cards: Self.threeCards, name: "three_cards_light")
    }

    @Test("three cards render in the dark theme")
    func threeCardsDark() {
        verify(theme: .dark, cards: Self.threeCards, name: "three_cards_dark")
    }

    @Test("three cards render in the sepia theme")
    func threeCardsSepia() {
        verify(theme: .sepia, cards: Self.threeCards, name: "three_cards_sepia")
    }

    @Test("eight cards overflow the visible sheet area")
    func eightCardsLight() {
        verify(theme: .light, cards: Self.eightCards, name: "eight_cards_light")
    }

    @Test("eight cards overflow in the dark theme")
    func eightCardsDark() {
        verify(theme: .dark, cards: Self.eightCards, name: "eight_cards_dark")
    }

    @Test("eight cards overflow in the sepia theme")
    func eightCardsSepia() {
        verify(theme: .sepia, cards: Self.eightCards, name: "eight_cards_sepia")
    }

    @Test("one card per category renders every badge glyph in light")
    func categoryCardsLight() {
        verify(theme: .light, cards: Self.categoryCards, height: 760, name: "category_cards_light")
    }

    @Test("one card per category renders every badge glyph in dark")
    func categoryCardsDark() {
        verify(theme: .dark, cards: Self.categoryCards, height: 760, name: "category_cards_dark")
    }

    @Test("one card per category renders every badge glyph in sepia")
    func categoryCardsSepia() {
        verify(theme: .sepia, cards: Self.categoryCards, height: 760, name: "category_cards_sepia")
    }

    @Test("per-category cards reflow their prose bodies at Dynamic Type XXL")
    func categoryCardsLightXXL() {
        verify(theme: .light, cards: Self.categoryCards, dynamicType: .xxLarge,
               height: 1180, name: "category_cards_light_xxl")
    }

    @Test("three cards render at Dynamic Type XXL")
    func threeCardsLightXXL() {
        verify(
            theme: .light,
            cards: Self.threeCards,
            dynamicType: .xxLarge,
            height: 720,
            name: "three_cards_light_xxl"
        )
    }

    @Test("the failed-dispatch state renders the message and retry button in light")
    func failedDispatchLight() {
        verify(
            theme: .light,
            cards: [],
            errorMessage: "No model is selected. Pick a model in Settings, then try again.",
            name: "failed_dispatch_light"
        )
    }

    @Test("the failed-dispatch state renders the message and retry button in dark")
    func failedDispatchDark() {
        verify(
            theme: .dark,
            cards: [],
            errorMessage: "No model is selected. Pick a model in Settings, then try again.",
            name: "failed_dispatch_dark"
        )
    }

    @Test("the failed-dispatch state renders the message and retry button in sepia")
    func failedDispatchSepia() {
        verify(
            theme: .sepia,
            cards: [],
            errorMessage: "No model is selected. Pick a model in Settings, then try again.",
            name: "failed_dispatch_sepia"
        )
    }

    @Test("the failed-dispatch state reflows the message + retry button at Dynamic Type XXL")
    func failedDispatchLightXXL() {
        verify(
            theme: .light,
            cards: [],
            errorMessage: "No model is selected. Pick a model in Settings, then try again.",
            dynamicType: .xxLarge,
            height: 720,
            name: "failed_dispatch_light_xxl"
        )
    }

    private func verify(
        theme themeID: SuperTheme.Identifier,
        cards: [AnnotationSheet.Card],
        isGenerating: Bool = false,
        errorMessage: String? = nil,
        dynamicType: DynamicTypeSize = .large,
        height: CGFloat = 600,
        name: String,
        function: String = #function
    ) {
        let theme = SuperTheme.make(themeID)
        let view = ZStack {
            theme.background
            AnnotationSheet(
                citation: Self.citation,
                cards: cards,
                onClose: {},
                onRegenerate: {},
                onAddAllToChat: {},
                onCardAddToChat: { _ in },
                onCardDelete: { _ in },
                onOpenReference: { _ in },
                onRetry: {},
                isGenerating: isGenerating,
                errorMessage: errorMessage,
                bottomInset: 0
            )
        }
        .frame(width: 393, height: height)
        .superTheme(theme)
        .dynamicTypeSize(dynamicType)

        let failure = verifySnapshot(
            of: view,
            as: .image(layout: .fixed(width: 393, height: height)),
            named: name,
            record: SnapshotEnvironment.isRecording ? .all : nil,
            testName: function
        )
        if let failure {
            Issue.record("\(name): \(failure)")
        }
    }
}
#endif
