#if canImport(UIKit)
import Core
import SnapshotTesting
import SwiftUI
import Testing
@testable import Bible

/// Snapshots of `AnnotationSheet` — the bottom sheet hosting the single
/// annotation card. Variants cover the empty / generating / error
/// states, the generating-over-populated precedence (a regenerate hides
/// the stale card behind the spinner), the populated single-card state
/// in light + dark, and Dynamic Type XXL passes for the surfaces whose
/// text reflows.
@Suite("AnnotationSheet snapshots")
@MainActor
struct AnnotationSheetSnapshotTests {
    /// Register Core's bundled brand fonts so the migrated JetBrains Mono /
    /// EB Garamond chrome faces resolve instead of baking the system
    /// fallback, and so this suite stays order-independent (registration is
    /// process-global; see `SnapshotFontRegistration`).
    init() { SnapshotFontRegistration.ensureRegistered() }

    private static let citation = "Romans 8:28-30"

    private static let card = AnnotationSheet.Card(
        title: "Romans 8:28-30",
        verseText: """
        We know that all things work together for good for those who \
        love God, for those who are called according to his purpose.
        """,
        summary: """
        ### Plain meaning
        Nothing — pain, loss, even death — falls outside what God can \
        weave toward the believer's good. **"Good"** means conformity \
        to Christ, not pleasant circumstances.

        ### Context
        "All things" includes the suffering Paul names earlier in the \
        chapter — creation's groaning, the believer's weakness in \
        prayer, even persecution.

        ### Cross-references
        The golden chain echoes the assurance of Ephesians 1:11, where \
        the same purpose-language frames the believer's inheritance.
        """,
        provenance: "Generated by AFM 3.0 · Nov 27, 2026"
    )

    // MARK: - Empty / generating / error states

    @Test("empty sheet renders in the light theme")
    func emptyLight() {
        verify(theme: .vellumLight, card: nil, name: "empty_light")
    }

    @Test("empty sheet renders in the dark theme")
    func emptyDark() {
        verify(theme: .vellumDark, card: nil, name: "empty_dark")
    }

    @Test("generating empty sheet shows the spinner-state bubble")
    func generatingLight() {
        verify(theme: .vellumLight, card: nil, isGenerating: true, name: "generating_light")
    }

    @Test("a regenerate over a populated card hides it behind the generating state in light")
    func generatingOverPopulatedLight() {
        verify(theme: .vellumLight, card: Self.card, isGenerating: true,
               name: "generating_over_populated_light")
    }

    @Test("a regenerate over a populated card hides it behind the generating state in dark")
    func generatingOverPopulatedDark() {
        verify(theme: .vellumDark, card: Self.card, isGenerating: true,
               name: "generating_over_populated_dark")
    }

    @Test("the failed-dispatch state renders the message and retry button in light")
    func failedDispatchLight() {
        verify(
            theme: .vellumLight,
            card: nil,
            errorMessage: "No model is selected. Pick a model in Settings, then try again.",
            name: "failed_dispatch_light"
        )
    }

    @Test("the failed-dispatch state renders the message and retry button in dark")
    func failedDispatchDark() {
        verify(
            theme: .vellumDark,
            card: nil,
            errorMessage: "No model is selected. Pick a model in Settings, then try again.",
            name: "failed_dispatch_dark"
        )
    }

    @Test("the failed-dispatch state reflows the message + retry button at Dynamic Type XXL")
    func failedDispatchLightXXL() {
        verify(
            theme: .vellumLight,
            card: nil,
            errorMessage: "No model is selected. Pick a model in Settings, then try again.",
            dynamicType: .xxLarge,
            height: 720,
            name: "failed_dispatch_light_xxl"
        )
    }

    // MARK: - Populated states

    @Test("the populated card renders in the light theme")
    func populatedLight() {
        verify(theme: .vellumLight, card: Self.card, height: 760, name: "populated_light")
    }

    @Test("the populated card renders in the dark theme")
    func populatedDark() {
        verify(theme: .vellumDark, card: Self.card, height: 760, name: "populated_dark")
    }

    @Test("the populated card reflows its prose at Dynamic Type XXL")
    func populatedLightXXL() {
        verify(
            theme: .vellumLight,
            card: Self.card,
            dynamicType: .xxLarge,
            height: 1100,
            name: "populated_light_xxl"
        )
    }

    private func verify(
        theme themeID: SuperTheme.Identifier,
        card: AnnotationSheet.Card?,
        isGenerating: Bool = false,
        errorMessage: String? = nil,
        dynamicType: DynamicTypeSize = .large,
        height: CGFloat = 600,
        name: String,
        function: String = #function
    ) {
        let theme = SuperTheme.make(themeID)
        let view = ZStack {
            theme.background
            AnnotationSheet(
                citation: Self.citation,
                card: card,
                onClose: {},
                onRegenerate: {},
                onAddToChat: {},
                onDelete: {},
                onOpenLink: { _ in },
                onRetry: {},
                isGenerating: isGenerating,
                errorMessage: errorMessage,
                bottomInset: 0
            )
        }
        .frame(width: 393, height: height)
        .superTheme(theme)
        .dynamicTypeSize(dynamicType)

        let failure = verifySnapshot(
            of: view,
            as: .image(layout: .fixed(width: 393, height: height)),
            named: name,
            record: SnapshotEnvironment.isRecording ? .all : nil,
            testName: function
        )
        if let failure {
            Issue.record("\(name): \(failure)")
        }
    }
}
#endif
