import Foundation
import GRDB

/// Immutable bundled scripture, generated by Scripts/generate_bible_text_sqlite.py.
/// Separate from migrated user state so static text never enters the sync store.
public struct BibleTextDatabase: Sendable {
    public let queue: DatabaseQueue

    public init(queue: DatabaseQueue) {
        self.queue = queue
    }

    /// Opens read-only to avoid SQLite creating sidecars inside the immutable app bundle.
    /// Throws BibleTextDatabaseError when missing or unreadable.
    public static func openBundled() throws -> BibleTextDatabase {
        guard let url = Bundle.module.url(forResource: "bible-text", withExtension: "sqlite") else {
            throw BibleTextDatabaseError.resourceMissing
        }
        var configuration = Configuration()
        configuration.readonly = true
        do {
            let queue = try DatabaseQueue(path: url.path, configuration: configuration)
            return BibleTextDatabase(queue: queue)
        } catch {
            throw BibleTextDatabaseError.openFailed(String(describing: error))
        }
    }

    /// Populates verse/FTS tables for tests; the structured chapter table stays empty.
    static func makeInMemory(verses: [Row]) throws -> BibleTextDatabase {
        let queue = try DatabaseQueue()
        try queue.write { db in
            try db.execute(sql: Self.schemaSQL)
            for verse in verses {
                try db.execute(
                    sql: "INSERT INTO verse(translation, bookId, chapter, verse, text) VALUES (?, ?, ?, ?, ?)",
                    arguments: [verse.translation, verse.bookId, verse.chapter, verse.verse, verse.text]
                )
            }
            try db.execute(sql: "INSERT INTO verse_fts(rowid, text) SELECT id, text FROM verse")
        }
        return BibleTextDatabase(queue: queue)
    }

    // Keep this schema aligned with the generator; bundled-consistency tests detect drift.
    static let schemaSQL = """
        CREATE TABLE chapter (
          translation TEXT NOT NULL,
          bookId      TEXT NOT NULL,
          number      INTEGER NOT NULL,
          json        TEXT NOT NULL,
          PRIMARY KEY (translation, bookId, number)
        );
        CREATE TABLE verse (
          id          INTEGER PRIMARY KEY,
          translation TEXT NOT NULL,
          bookId      TEXT NOT NULL,
          chapter     INTEGER NOT NULL,
          verse       INTEGER NOT NULL,
          text        TEXT NOT NULL
        );
        CREATE INDEX verse_on_translation_bookId_chapter
          ON verse(translation, bookId, chapter);
        CREATE VIRTUAL TABLE verse_fts USING fts5(
          text,
          content='verse',
          content_rowid='id',
          tokenize='porter unicode61'
        );
        """

    /// Populates structured chapters for tests; verse/FTS tables stay empty.
    static func makeInMemory(chapters: [ChapterRow]) throws -> BibleTextDatabase {
        let queue = try DatabaseQueue()
        try queue.write { db in
            try db.execute(sql: Self.schemaSQL)
            for chapter in chapters {
                try db.execute(
                    sql: "INSERT INTO chapter(translation, bookId, number, json) VALUES (?, ?, ?, ?)",
                    arguments: [chapter.translation, chapter.bookId, chapter.number, chapter.json]
                )
            }
        }
        return BibleTextDatabase(queue: queue)
    }

    struct Row {
        let translation: String
        let bookId: String
        let chapter: Int
        let verse: Int
        let text: String

        init(translation: BibleTranslation, bookId: String, chapter: Int, verse: Int, text: String) {
            self.translation = translation.rawValue
            self.bookId = bookId
            self.chapter = chapter
            self.verse = verse
            self.text = text
        }
    }

    /// Encode BibleChapter into json for a loader round trip.
    struct ChapterRow {
        let translation: String
        let bookId: String
        let number: Int
        let json: String

        init(translation: BibleTranslation, bookId: String, number: Int, chapter: BibleChapter) throws {
            self.translation = translation.rawValue
            self.bookId = bookId
            self.number = number
            self.json = String(decoding: try JSONEncoder().encode(chapter), as: UTF8.self)
        }
    }
}

public enum BibleTextDatabaseError: Error, Sendable, Equatable {
    case resourceMissing
    case openFailed(String)
}
